####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

from router import Router
import json
from packet import Packet


class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.neighbors = {}
        self.neighbors_dvs = {}
        self.distance = {addr: 0}
        self.nexthop = {}
        pass
    
    def broadcast_dv(self):
        content = json.dumps(self.distance)
        for port in self.neighbors:
            packet = Packet(Packet.ROUTING, self.addr, self.neighbors[port][0], content)
            self.send(port, packet)

    def recompute_dv(self):
        new_distances = {self.addr : 0}
        new_nexthop = {}

        for port, (endpoint, link_cost) in self.neighbors.items():
            if endpoint not in new_distances or link_cost < new_distances[endpoint]:
                new_distances[endpoint] = link_cost
                new_nexthop[endpoint] = port

            for dst, cost in self.neighbors_dvs[port].items():
                total = link_cost + cost
                if dst not in new_distances or total < new_distances[dst]:
                    new_distances[dst] = total
                    new_nexthop[dst] = port

        changed = (new_distances != self.distance)
        self.distance = new_distances
        self.nexthop = new_nexthop
        return changed 


    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.nexthop:
                self.send(self.nexthop[packet.dst_addr], packet)
            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors
            recv_dv = json.loads(packet.content)

            if recv_dv == self.neighbors_dvs.get(port):
                return
            
            self.neighbors_dvs[port] = recv_dv
            if self.recompute_dv():
                self.broadcast_dv()
            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        self.neighbors[port] = (endpoint, cost)
        self.neighbors_dvs[port] = {}
        
        if self.recompute_dv():
            self.broadcast_dv()
        pass

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        if port in self.neighbors:
            del self.neighbors[port]
        if port in self.neighbors_dvs:
            del self.neighbors_dvs[port]

        self.recompute_dv()
        self.broadcast_dv()
        pass

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors
            self.broadcast_dv()
            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return (f"DVrouter(addr={self.addr})\n"
            f"  distancs={self.distance}\n"
            f"  nexthop={self.nexthop}\n"
            f"  neighbors={self.neighbors}")
